artifactes_root : artifactes

data_ingestion:
  root_dir : artifactes/data_ingestion
  source_URL : 'https://github.com/dhruv1n30/Data/raw/refs/heads/main/winequality-red.zip'
  local_data_file: artifactes/data_ingestion/data.zip
  unzip_dir: artifactes/data_ingestion/

data_validation:
  root_dir: artifactes/data_validation
  unzip_data_dir: artifactes/data_ingestion/winequality-red.csv
  STATUS_FILE: artifactes/data_validation/status.txt

data_transformation:
  root_dir: artifactes/data_transformation
  data_path: artifactes/data_ingestion/winequality-red.csv

model_trainer:
  root_dir: artifactes/model_trainer
  train_data_path: artifactes/data_transformation/train.csv
  test_data_path: artifactes/data_transformation/test.csv
  model_name: model.joblib


model_evaluation:
  root_dir: artifactes/model_evaluation
  test_data_path: artifactes/data_transformation/test.csv
  model_path: artifactes/model_trainer/model.joblib
  metric_file_name: artifactes/model_evaluation/metrics.json